@startuml class_diagram

class Action {

    {static} Vehicle vehicle

    +void {abstract} move_to_pos(tuple node_position)
    +void {abstract} cancel_goal()
    +void {abstract} pick()
    +void {abstract} place()

}

class Vehicle {

    {static} Comm comm
    {static} Action action
    {static} int id
    {static} tuple depot_station
    {static} str node
    {static} str status
    
    {static} float x_loc
    {static} float y_loc
    {static} float theta
    {static} float speed
    {static} float battery_status

    {static} Thread task_executer
    {static} Thread status_updater
    {static} Thread alive_checker
    {static} Thread progress_tracker
    {static} Thread performance_monitor

    +void {abstract} task_executer()
    +void {abstract} execute_task()
    +void {abstract} status_updater()
    +void {abstract} alive_checker()
    +void {abstract} progress_tracker()
    +void {abstract} performance_monitor()

}

class TA_Agent {

    {static} Comm comm
    {static} Thread task_collector
    {static} Thread task_allocator
    {static} Thread task_switcher
    {static} Thread task_scheduler

    +void {abstract} task_collector()
    +void {abstract} task_allocator()
    +void {abstract} task_switcher()
    +void {abstract} task_scheduler()
    +list bid {abstract} compute_bid(local_task_list, new_task)
 
}

class RO_Agent {

    {static} Comm comm
    {static} Thread route_planner
    {static} Thread route_evaporator

    +void {abstract} route_planner()
    +void {abstract} route_evaporator()
    +void {abstract} plan_executing_task()
    +void {abstract} plan_local_tasks()
    
}

class RM_Agent {

    {static} Comm comm
    {static} Thread resource_optimizer
    {static} Thread resource_thresholder

    +void {abstract} resource_optimizer()
    +void {abstract} resource_thresholder()

}

Vehicle "1" o-- Action : aggregation

@enduml