@startuml class_diagram

class TA_Agent {

    {static} Comm comm
    {static} Thread task_collector
    {static} Thread task_allocator
    {static} Thread task_switcher
    {static} Thread task_scheduler

    +{abstract} task_collector()
    +{abstract} task_allocator()
    +{abstract} task_switcher()
    +{abstract} task_scheduler()
    +{abstract} compute_bid()
 
}

class RO_Agent {

    {static} Comm comm
    {static} Thread route_planner
    {static} Thread route_evaporator

    +{abstract} route_planner()
    +{abstract} route_evaporator()
    +{abstract} plan_executing_task()
    +{abstract} plan_local_tasks()
    
}

class RM_Agent {

    {static} Comm comm
    {static} Thread resource_optimizer
    {static} Thread resource_thresholder

    +{abstract} resource_optimizer()
    +{abstract} resource_thresholder()
    +{abstract} resource_consumption()

}

TA_Agent -right[hidden]-> RO_Agent
RO_Agent -right[hidden]-> RM_Agent

@enduml