@startuml connection_diagram

package "Coordination Framework" {

    [Communication_layer]
    [MA_Agent]
    [TA_Agent]
    [RO_Agent]
    [RM_Agent]

}

database "Database" {

    [global_robot_list]
    [global_task_list]

}

[Robot] <-> [Communication_layer] : ROS
[Robot] --> Action

[global_task_list] -> [Webserver] : SQL
[Webserver] -> HTTP

[TA_Agent] <--> [Communication_layer] : SQL
[RO_Agent] <--> [Communication_layer] : SQL
[RM_Agent] <--> [Communication_layer] : SQL
[MA_Agent] <--> [Communication_layer] : SQL

[Communication_layer] <--> [global_task_list] : SQL
[Communication_layer] <--> [global_robot_list] : SQL

[MES] -> [Communication_layer] : Wifi

@enduml