@startuml connection_diagram

package "Decentral Fleet Management Framework" {

    [Communication_layer]
    [Vehicle_Agent]
    [TA_Agent]
    [RO_Agent]
    [RM_Agent]

}

database "MySql" {

    [global_robot_list]
    [global_task_list]

}

[global_robot_list] -[hidden]- [global_task_list]
[Webserver] -[hidden]- [Vehicle]

[global_task_list] -> [Vehicle]
[Vehicle] -> [global_robot_list]
[Vehicle] -> Action

[global_task_list] -> [Webserver]
[global_robot_list] -> [Webserver]
[Webserver] -> HTTP

[TA_Agent] <--> [Communication_layer]
[RO_Agent] <--> [Communication_layer]
[RM_Agent] <--> [Communication_layer]
[Vehicle_Agent] <--> [Communication_layer]

[Communication_layer] <--> [global_task_list]
[Communication_layer] <--> [global_robot_list]

[MES] --> [TA_Agent]

@enduml