#!/usr/bin/env python3

import signal
import rospy
from robotino_core.agv.AGV_ROS import AGV_ROS

if __name__== '__main__':

	# Get id
	id = int(rospy.get_param('/robotino_core_node/id'))

	# Params file
	params_file = 'setup' + str(id) + '.yaml'

	# Start AGV ROS
	rospy.init_node("robotino_" + str(id))
	agv_ros = AGV_ROS(params_file)
	threads = agv_ros.threads

	# Start processes
	for thread in threads:
		thread.start()

	# Exit handler function
	def signal_handler(_, __):
		agv_ros.exit_event.set()
		rospy.signal_shutdown('CTRL-C pressed.')

	# Exit handler
	signal.signal(signal.SIGINT, signal_handler)

	# Spin
	rospy.spin()
