#!/usr/bin/env python3

import rospy
from robotino_core.agv.AGV_Main import AGV

if __name__ == '__main__':

    # Init AGV object
    try:
        AGV()
    except:
        rospy.loginfo("Shutdown program.")
